includes:
  - https://github.ibm.com/cloud-docs/account
  - https://github.ibm.com/cloud-docs/cli
  - https://github.ibm.com/cloud-docs/vmware
  - https://github.ibm.com/cloud-docs/FileStorage
  - https://github.ibm.com/cloud-docs-solutions/infrastructure-hub